/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posjavagui;
import java.time.LocalDate;
import posjavagui.backend.Transaction;
import posjavagui.backend.dbHelper;
import java.util.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author U
 */
public class salesReport extends javax.swing.JFrame {

    /**
     * Creates new form salesReport
     */
    public salesReport() {
        initComponents();
        
        // kunin ang date ngayong araw
        String Date[] = LocalDate.now().toString().split("-");
        String Day = Date[2];
        String Month = Date[1];
        String Year = Date[0];
        
        // i display ang date ngayong araw sa  text field
        dsDay.setText(Day);
        dsMonth.setText(Month);
        dsYear.setText(Year);
        msMonth.setText(Month);
        msYear.setText(Year);
    }
    
    // kunin kung anong month name ng ipapasang number
     public  String getMonthName(String monthNumber) {
        String[] months = {
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        };

        try {
            int index = Integer.parseInt(monthNumber);
            if (index >= 1 && index <= 12) {
                return months[index - 1]; // Adjust for 0-based index
            } else {
                return "Invalid month number";
            }
        } catch (NumberFormatException e) {
            return "Invalid input";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dsMonth = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dsDay = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dsYear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        daySalesBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        msMonth = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        msYear = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        monthSalesBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalVariable = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dateVariable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Sales Report");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "transactionId", "date", "cash", "change", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("month: ");

        jLabel3.setText("day: ");

        jLabel4.setText("year: ");

        daySalesBtn.setText("day sales report");
        daySalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daySalesBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Day Sales");

        msMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msMonthActionPerformed(evt);
            }
        });

        jLabel6.setText("month: ");

        jLabel7.setText("year: ");

        monthSalesBtn.setText("month sales report");
        monthSalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthSalesBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Month Sales");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("DATE: ");

        totalVariable.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        totalVariable.setText("0");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setText("TOTAL SALES: P");

        dateVariable.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dateVariable.setText("NO SELECTED DATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dsMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dsDay, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dsYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(415, 415, 415)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthSalesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(msMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(msYear)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(daySalesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel5))
                                .addGap(221, 221, 221)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalVariable)
                                .addGap(149, 149, 149)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateVariable)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dsMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dsDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dsYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daySalesBtn)
                    .addComponent(monthSalesBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalVariable)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(dateVariable))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msMonthActionPerformed

    private void daySalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daySalesBtnActionPerformed
        // kunin ang user input
        int day = Integer.parseInt(dsDay.getText());
        int month = Integer.parseInt(dsMonth.getText());
        int year = Integer.parseInt(dsYear.getText());
        
        // i reset ang value ng table 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int totalSales = 0;
        
        dbHelper myDb = new dbHelper();
        
        // kunin lahat ng transactions
        List<Transaction> transactions = myDb.getTransactions();
        
        // mag iterate sa transactions
        for(Transaction transaction : transactions)
        {
            // kunin ang date kung kelan naganap ang transaction
            String transactionDate[] = transaction.getDate().split("-");
            int transactionDay = Integer.parseInt(transactionDate[2]);
            int transactionMonth = Integer.parseInt(transactionDate[1]);
            int transactionYear = Integer.parseInt(transactionDate[0]);
            
            // i check kung yung user input na date ay equal sa date ng transaction pag equal sila i add sa table ang transaction pag hindi ay wag ito i add sa table
            if(day == transactionDay && month == transactionMonth && year == transactionYear)
            {
                // i add yung recipt sa container
                model.addRow(new Object[]{
                    transaction.getTransactionId(),
                    transaction.getDate(),
                    transaction.getCash(),
                    transaction.getPaymentChange(),
                    transaction.getTotal()
                });
                
                // i add yunfg total ng transaction sa total sales
                totalSales += transaction.getTotal();
            }
            
        }
        
        // set ng value sa total at sa date
        totalVariable.setText(Integer.toString(totalSales));
        dateVariable.setText(getMonthName(Integer.toString(month)) + " " + day + " " + year);
        
        
    }//GEN-LAST:event_daySalesBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          this.dispose(); 
        shopFrame shopPage = new shopFrame();
        shopPage.setLocationRelativeTo(null);
        shopPage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void monthSalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthSalesBtnActionPerformed
 
        String month = msMonth.getText();
        String year = msYear.getText();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        int totalSales = 0;
        
        dbHelper myDb = new dbHelper();
        
        List<Transaction> transactions = myDb.getTransactions();
        
        for(Transaction transaction : transactions)
        {
            // kunin ang date kung kelan naganap ang transaction
            String transactionDate[] = transaction.getDate().split("-");
            String transactionDay = transactionDate[2];
            String transactionMonth = transactionDate[1];
            String transactionYear = transactionDate[0];
            
            // i check kung yung user input na date ay equal sa date ng transaction pag equal sila i add sa table ang transaction pag hindi ay wag ito i add sa table
            if(month.equals(transactionMonth) && year.equals(transactionYear))
            {
                model.addRow(new Object[]{
                    transaction.getTransactionId(),
                    transaction.getDate(),
                    transaction.getCash(),
                    transaction.getPaymentChange(),
                    transaction.getTotal()
                });
                
                totalSales += transaction.getTotal();
            }
            
        }
        
         // set ng value sa total at sa date
        totalVariable.setText(Integer.toString(totalSales));
        dateVariable.setText("month of " + getMonthName(month) + " " + year);
    }//GEN-LAST:event_monthSalesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateVariable;
    private javax.swing.JButton daySalesBtn;
    private javax.swing.JTextField dsDay;
    private javax.swing.JTextField dsMonth;
    private javax.swing.JTextField dsYear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton monthSalesBtn;
    private javax.swing.JTextField msMonth;
    private javax.swing.JTextField msYear;
    private javax.swing.JLabel totalVariable;
    // End of variables declaration//GEN-END:variables
}
